tcp:
  routers:
    route-to-router:
      rule: "HostSNI(`{{env "ROUTER_SUBDOMAIN"}}{{env "BASE_DOMAIN"}}`)"
      service: router
      priority: 1000
      tls:
        passthrough: true

  services:
    router:
      loadBalancer:
        servers:
        - address: "192.168.1.1:443"
